# Generated by Django 5.0.2 on 2024-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_head_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/employee/%Y/%M/%d'),
        ),
    ]
