# Generated by Django 5.0.2 on 2024-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfrequency',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
