# Generated by Django 5.0.2 on 2024-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Tenant', 'Tenant')], default='Staff', max_length=255),
        ),
    ]
