# Generated by Django 5.0.2 on 2024-06-30 11:51

import django.db.models.deletion
import utils.hostel_utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Amenity')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='RoomCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Room Categories',
                'db_table': 'roomcategories',
            },
        ),
        migrations.CreateModel(
            name='HostelAmenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.amenities')),
            ],
            options={
                'verbose_name_plural': 'Hostel Amenities',
                'db_table': 'hostelamenities',
            },
        ),
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Hostel name')),
                ('nameslug', models.SlugField(blank=True, unique=True)),
                ('rating', models.FloatField(default=0)),
                ('regNumber', models.CharField(blank=True, max_length=255, verbose_name='Hostel Reg. Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postalcode', models.CharField(blank=True, max_length=255, verbose_name='Postal Code/Zip Code')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(related_name='hostels', through='housing.HostelAmenities', to='housing.amenities')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='accounts.city')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostels',
            },
        ),
        migrations.CreateModel(
            name='HostelRoomTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('number_of_beds', models.PositiveBigIntegerField(default=1)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtypes', to='housing.hostels')),
            ],
            options={
                'verbose_name_plural': 'Hostel Room Types',
                'db_table': 'hostelroomtypes',
            },
        ),
        migrations.CreateModel(
            name='HostelPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to=utils.hostel_utils.generate_hostel_image_upload_path)),
                ('dateuploaded', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('uploadedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='housing.hostels')),
            ],
            options={
                'verbose_name_plural': 'Hostel Photos',
                'db_table': 'hostelphotos',
            },
        ),
        migrations.AddField(
            model_name='hostelamenities',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.hostels'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_reviews', to='housing.hostels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='hostels',
            name='reviews',
            field=models.ManyToManyField(related_name='hostels', to='housing.reviews'),
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_type', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Room Type')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.roomcategories')),
            ],
            options={
                'verbose_name_plural': 'Room Types',
                'db_table': 'roomtypes',
            },
        ),
        migrations.AddField(
            model_name='hostels',
            name='room_types',
            field=models.ManyToManyField(related_name='hostels', through='housing.HostelRoomTypes', to='housing.roomtypes'),
        ),
        migrations.AddField(
            model_name='hostelroomtypes',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_hostels', to='housing.roomtypes'),
        ),
    ]
