# Generated by Django 5.0.2 on 2024-02-23 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='employee.employee'),
        ),
    ]
