# Generated by Django 5.0.2 on 2024-02-23 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_hostel_created_by'),
        ('school', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.country'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='request_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='housing.requeststatus'),
        ),
    ]
