# Generated by Django 5.0.2 on 2024-02-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_room_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housing.hostel'),
            preserve_default=False,
        ),
    ]
