# Generated by Django 5.0.2 on 2024-03-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('housing', '0002_badge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateDocumentVerification',
            new_name='DocumentVerificationPro',
        ),
        migrations.AlterModelTable(
            name='documentverificationpro',
            table='documentverificationpro',
        ),
    ]
