# Generated by Django 5.0.2 on 2024-07-16 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_hostelamenities_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bed_type', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Bed Type',
                'verbose_name_plural': 'Bed Types',
                'db_table': 'bedtypes',
            },
        ),
        migrations.RenameField(
            model_name='hostelroomtypes',
            old_name='number_of_beds',
            new_name='bed_per_room',
        ),
        migrations.AddField(
            model_name='hostelroomtypes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.hostels')),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.bedtypes')),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_number', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.hostels')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.hostelroomtypes')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomBeds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.beds')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.rooms')),
            ],
        ),
    ]
