# Generated by Django 5.0.2 on 2024-02-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrequest',
            name='preferred_blocks',
        ),
        migrations.RemoveField(
            model_name='roomrequest',
            name='preferred_floors',
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='duration_of_stay',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
