# Generated by Django 5.0.2 on 2024-03-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_rename_updatedocumentverification_documentverificationpro_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badge',
            table='badge',
        ),
    ]
