# Generated by Django 5.0.2 on 2024-03-30 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_badge_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifyproperty',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
