# Generated by Django 5.0.2 on 2024-02-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmate', '0001_initial'),
        ('housing', '0004_remove_roomrequest_preferred_blocks_and_more'),
        ('school', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gender'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='move_in_date_earliest',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Move In Date (Earliest By)'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='move_in_date_latest',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Move In Date (Latest By)'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='preferred_amenities',
            field=models.ManyToManyField(blank=True, to='housing.hostelamenities'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='preferred_facilities',
            field=models.ManyToManyField(blank=True, to='housing.facility'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='preferred_hostels',
            field=models.ManyToManyField(blank=True, to='housing.hostel'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='preferred_payment_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finmate.paymentfrequency'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='preferred_room_types',
            field=models.ManyToManyField(blank=True, to='housing.roomtype'),
        ),
    ]
