# Generated by Django 5.0.2 on 2024-07-25 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_bedtypes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.floors'),
        ),
        migrations.CreateModel(
            name='HostelEmployees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.hostels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hostel Employee',
                'verbose_name_plural': 'Hostel Employees',
                'db_table': 'hostelemployees',
            },
        ),
    ]
