# Generated by Django 5.0.2 on 2024-02-13 13:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_block_block_id'),
        ('school', '0002_city_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='company',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='date_established',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.hostelstatus'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gender')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.nationality')),
            ],
        ),
    ]
