# Generated by Django 5.0.2 on 2024-02-23 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_alter_roomrequest_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='move_in_date_latest',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Move In Date (Latest By)'),
            preserve_default=False,
        ),
    ]
