# Generated by Django 5.0.2 on 2024-07-25 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_alter_hostels_createdby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='createdby',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel', to=settings.AUTH_USER_MODEL),
        ),
    ]
