# Generated by Django 5.0.2 on 2024-02-20 00:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmate', '0001_initial'),
        ('housing', '0006_remove_tenant_name_tenant_user'),
        ('school', '0002_city_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomOfferStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='amenities',
            field=models.ManyToManyField(to='housing.hostelamenities'),
        ),
        migrations.CreateModel(
            name='RoomOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=255)),
                ('date_offered', models.DateTimeField(auto_now_add=True)),
                ('rooms_offered', models.ManyToManyField(to='housing.room')),
                ('offer_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.roomofferstatus')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomofferresponse_number', models.CharField(max_length=255)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('rent_paid', models.BooleanField(default=False)),
                ('offer_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.roomoffer')),
                ('offer_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.offerresponse')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_email', models.EmailField(max_length=254)),
                ('tenant_phone', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('number_of_beds_required', models.PositiveIntegerField(default=1)),
                ('move_in_date_earliest', models.DateTimeField(verbose_name='Move In Date (Earliest By)')),
                ('move_in_date_latest', models.DateTimeField(verbose_name='Move In Date (Latest By)')),
                ('duration_of_stay', models.PositiveIntegerField(default=1)),
                ('min_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gender')),
                ('preferred_amenities', models.ManyToManyField(to='housing.hostelamenities')),
                ('preferred_blocks', models.ManyToManyField(to='housing.block')),
                ('preferred_facilities', models.ManyToManyField(to='housing.facility')),
                ('preferred_floors', models.ManyToManyField(to='housing.floor')),
                ('preferred_hostels', models.ManyToManyField(to='housing.hostel')),
                ('preferred_payment_frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finmate.paymentfrequency')),
                ('preferred_room_types', models.ManyToManyField(to='housing.roomtype')),
                ('request_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='housing.roomstatus')),
            ],
        ),
        migrations.AddField(
            model_name='roomoffer',
            name='room_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.roomrequest'),
        ),
        migrations.CreateModel(
            name='TenantRoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.date.today)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.tenant')),
            ],
        ),
    ]
