# Generated by Django 5.0.2 on 2024-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_documentverificationpro_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelemployeealloc',
            name='employee_code',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hostelemployeealloc',
            name='hostel_code',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
