# Generated by Django 5.0.2 on 2024-02-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_alter_roomrequest_move_in_date_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='move_in_date_latest',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Move In Date (Latest By)'),
        ),
    ]
