# Generated by Django 5.0.2 on 2024-02-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_alter_roomrequest_move_in_date_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='duration_of_stay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
