# Generated by Django 5.0.2 on 2024-07-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_alter_hostels_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='housing.floors'),
        ),
    ]
