# Generated by Django 5.0.2 on 2024-04-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_options_employee_created_at'),
        ('housing', '0007_hostelemployeealloc_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostelemployeealloc',
            unique_together={('hostel', 'role', 'employee', 'active')},
        ),
    ]
