# Generated by Django 5.0.2 on 2024-04-03 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_alter_hostelemployeealloc_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostelemployeealloc',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hostelemployeealloc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
