# Generated by Django 5.0.2 on 2024-02-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_alter_roomrequest_duration_of_stay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomrequest',
            old_name='request_number',
            new_name='request_id',
        ),
    ]
