# Generated by Django 5.0.2 on 2024-02-20 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_alter_tenantroomassignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housing.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
