# Generated by Django 5.0.2 on 2024-04-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_alter_hostelemployeealloc_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housing.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_cost_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
