# Generated by Django 5.0.2 on 2024-02-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_rename_request_number_roomrequest_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomoffer',
            name='date_offered',
        ),
        migrations.RemoveField(
            model_name='roomoffer',
            name='offer_status',
        ),
        migrations.RemoveField(
            model_name='roomoffer',
            name='rooms_offered',
        ),
        migrations.CreateModel(
            name='RoomOfferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_offered', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('offer_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.roomofferstatus')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.room')),
                ('room_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.roomoffer')),
            ],
        ),
        migrations.AddField(
            model_name='roomoffer',
            name='rooms_offered_new',
            field=models.ManyToManyField(through='housing.RoomOfferDetails', to='housing.room'),
        ),
    ]
