# Generated by Django 5.0.2 on 2024-07-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_neighborhoods'),
        ('housing', '0009_alter_rooms_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='hms.neighborhoods', verbose_name='neighborhood'),
        ),
        migrations.AlterField(
            model_name='hostelamenities',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosstels', to='housing.amenities'),
        ),
        migrations.AlterField(
            model_name='hostelamenities',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ammenities', to='housing.hostels'),
        ),
    ]
