# Generated by Django 5.0.2 on 2024-02-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_floor_block_floor_floor_id_alter_hostel_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.block'),
        ),
    ]
