# Generated by Django 5.0.2 on 2024-07-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_hostels_neighborhood_alter_hostelamenities_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelamenities',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.amenities'),
        ),
        migrations.AlterField(
            model_name='hostelamenities',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.hostels'),
        ),
    ]
