# Generated by Django 5.0.2 on 2024-04-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_roomtype_hostel_roomtype_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupancy_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='housing.occupancystatus'),
        ),
    ]
