# Generated by Django 5.0.2 on 2024-03-09 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('housing', '0011_rename_cost_facility_base_price_block_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VericationDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='', verbose_name='Attach Document')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('verification_document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.vericationdocumenttype')),
            ],
        ),
    ]
