# Generated by Django 5.0.2 on 2024-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0012_roomtypes_room_type_code_alter_roomtypes_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='housing.reviews'),
        ),
    ]
