# Generated by Django 5.0.2 on 2024-03-09 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('housing', '0013_propertytype_room_created_at_room_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifyproperty',
            old_name='document',
            new_name='attachment',
        ),
        migrations.AddField(
            model_name='verifyproperty',
            name='verifypropertyinfo',
            field=models.TextField(blank=True),
        ),
    ]
