# Generated by Django 5.0.2 on 2024-04-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_options_employee_created_at'),
        ('housing', '0013_block_room_cost_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housing.hostel'),
            preserve_default=False,
        ),
    ]
