# Generated by Django 5.0.2 on 2024-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0014_application_applicationstatus_applicationhostel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
    ]
