# Generated by Django 5.0.2 on 2024-04-08 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_options_employee_created_at'),
        ('housing', '0014_facility_added_by_facility_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteltenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteltenant',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoomItemAlloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.facility')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.room')),
            ],
        ),
    ]
