# Generated by Django 5.0.2 on 2024-03-09 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('housing', '0014_rename_document_verifyproperty_attachment_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='verifyproperty',
            name='attachment',
            field=models.FileField(upload_to='media/verification_document/%Y/%m/%d', verbose_name='Attach Document'),
        ),
    ]
