# Generated by Django 5.0.2 on 2024-07-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0015_alter_application_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationhostel',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='applicationhostel',
            old_name='hostel_id',
            new_name='hostel',
        ),
        migrations.RenameField(
            model_name='applicationhostel',
            old_name='room_type_id',
            new_name='room_type',
        ),
    ]
