# Generated by Django 5.0.2 on 2024-04-17 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0015_hosteltenant_created_at_hosteltenant_created_by_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('street_address', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('min_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('student', models.BooleanField()),
                ('rent_begin', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Move-in Date')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.city')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.gender')),
                ('hostels', models.ManyToManyField(to='housing.hostel')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.nationality')),
                ('room_types', models.ManyToManyField(to='housing.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.roomcategory'),
        ),
    ]
