# Generated by Django 5.0.2 on 2024-07-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0016_rename_application_id_applicationhostel_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationhostel',
            old_name='room_type',
            new_name='room_types',
        ),
    ]
