# Generated by Django 5.0.2 on 2024-08-01 08:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_university'),
        ('housing', '0017_rename_room_type_applicationhostel_room_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationhostel',
            name='room_types',
        ),
        migrations.AddField(
            model_name='applicationhostel',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.hostelroomtypes', verbose_name='room types'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Tenant ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('next_of_kin', models.CharField(blank=True, max_length=255, verbose_name='Next of Kin')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.gender', verbose_name='')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='HousingOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Offer ID')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='Name of Applicant')),
                ('email', models.EmailField(max_length=254, verbose_name='Applicant Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Applicant Phone Number')),
                ('date_offered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Offered')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('applicationhostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.applicationhostel', verbose_name='hostel application')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='housing.hostels', verbose_name='hostel')),
                ('offered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.rooms', verbose_name='')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.roomtypes', verbose_name='')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.applicationstatus', verbose_name='')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'housing Offer',
                'verbose_name_plural': 'housing Offers',
                'db_table': 'housingoffer',
            },
        ),
    ]
