# Generated by Django 5.0.2 on 2024-04-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0017_hostelapplication_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelapplication',
            options={'verbose_name': 'Hostel Application', 'verbose_name_plural': 'Hostel Applications'},
        ),
        migrations.AlterModelTable(
            name='hostelapplication',
            table='hostelapplication',
        ),
    ]
