# Generated by Django 5.0.2 on 2024-03-25 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('housing', '0017_room_created_at_room_created_by_roomrequest_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='verifyproperty',
            name='property_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UpdateDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedocumentverification_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_of_update', models.DateField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('last_update_message', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('verification_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.documentverificationstatus')),
                ('verify_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.verifyproperty')),
            ],
        ),
    ]
