# Generated by Django 5.0.2 on 2024-08-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0018_remove_applicationhostel_room_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingoffer',
            old_name='applicationhostel',
            new_name='application_hostel',
        ),
    ]
