# Generated by Django 5.0.2 on 2024-03-25 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('housing', '0018_documentverificationstatus_room_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyproperty',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
