# Generated by Django 5.0.2 on 2024-03-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('housing', '0020_room_created_at_room_created_by_roomrequest_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verifyproperty',
            unique_together={('application_id', 'verification_document_type')},
        ),
    ]
